Repository devstream-io/devstream, pull requests merged in 2021-12, with the labels that each got.

#28 feat: state management support
  .gitignore
  Makefile
  cmd/devstream/install.go
  internal/pkg/backend/backend.go
  internal/pkg/backend/local/local.go
  internal/pkg/statemanager/manager.go
  internal/pkg/statemanager/manager_test.go
  internal/pkg/statemanager/state.go
Labels: enhancement, good first issue

#32 plugin management support
  go.mod
  go.sum
  internal/pkg/download/download.go
  internal/pkg/download/download_test.go
  internal/pkg/download/manager.go
  internal/pkg/download/releaseinfo.go
  internal/pkg/plugin/plugin.go
Labels: enhancement, good first issue

#37 docs: change CLI name
  README.md
Labels: doc

#35 an "action calculation" feature to determine the next action.
  cmd/argocd/main.go
  cmd/argocdapp/main.go
  cmd/devstream/install.go
  cmd/githubactions/main.go
  go.mod
  go.sum
  internal/pkg/argocd/install.go
  internal/pkg/argocdapp/install.go
  internal/pkg/githubactions/install.go
  internal/pkg/plan/plan.go
  internal/pkg/plan/plan_test.go
  internal/pkg/plugin/plugin.go
  internal/pkg/statemanager/manager.go
  internal/pkg/statemanager/manager_test.go
  internal/pkg/statemanager/state.go
Labels: enhancement

#41 rename CLI name & package names
  .gitignore
  Makefile
  cmd/devstream/init.go
  cmd/devstream/install.go
  cmd/devstream/main.go
  docs/architecture.md
  internal/pkg/configloader/config.go
  internal/pkg/planmanager/plan.go
  internal/pkg/planmanager/plan_test.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/pluginmanager/manager.go
Labels: enhancement

#42 docs: unified naming and etc.
  Makefile
  README.md
Labels: doc

#45 fix: let helm to create namespace for argocd if it does not exist
  examples/config.yaml
  go.mod
  go.sum
  internal/pkg/argocd/argocd.go
  internal/pkg/planmanager/plan.go
Labels: bug

#46 feat: implement uninstall/reinstall interface for argocd
  .gitignore
  cmd/argocd/main.go
  cmd/devstream/install.go
  internal/pkg/argocd/argocd.go
  internal/pkg/argocd/install.go
  internal/pkg/argocd/reinstall.go
  internal/pkg/argocd/uninstall.go
  internal/pkg/planmanager/change.go
  internal/pkg/planmanager/plan.go
  internal/pkg/planmanager/result.go
Labels: enhancement

#52 fix: some reflactoring with download-client/plugin-engine
  internal/pkg/pluginengine/plugin.go
  internal/pkg/pluginmanager/downloader.go
  internal/pkg/pluginmanager/manager.go
Labels: bug

#59 fix: Supplement the fix for #54
  internal/pkg/planmanager/result.go
Labels: bug

#61 feat: caching go dependencies to speed up workflows
  .github/workflows/pr-builder.yml
Labels: enhancement

#62 reflactor: do some optimizations to githubactions package
  internal/pkg/githubactions/githubactions.go
  internal/pkg/githubactions/install.go
  internal/pkg/githubactions/param.go
  internal/pkg/githubactions/params.go
  internal/pkg/githubactions/reinstall.go
  internal/pkg/githubactions/uninstall.go
Labels: refactor

#63 doc: update architecture overview
  docs/architecture.md
  docs/images/architecture-overview.png
Labels: documentation

#69 feat: add support for Python and Nodejs with GitHub Actions plugin
  examples/config.yaml
  internal/pkg/githubactions/githubactions.go
  internal/pkg/githubactions/golang/templates.go
  internal/pkg/githubactions/install.go
  internal/pkg/githubactions/nodejs/templates.go
  internal/pkg/githubactions/param.go
  internal/pkg/githubactions/python/templates.go
  internal/pkg/githubactions/reinstall.go
  internal/pkg/githubactions/uninstall.go
  internal/pkg/githubactions/workflow.go
Labels: enhancement

#72 refactor: make Makefile better
  Makefile
Labels: refactor

#74 fix: some tips with githubactions for golang
  cmd/devstream/main.go
  internal/pkg/githubactions/githubactions.go
  internal/pkg/githubactions/golang/templates.go
  internal/pkg/githubactions/install.go
  internal/pkg/githubactions/reinstall.go
  internal/pkg/githubactions/uninstall.go
Labels: bug

#75 refactor: do some refactor with argocdapp plugin
  internal/pkg/argocdapp/argocdapp.go
  internal/pkg/argocdapp/install.go
  internal/pkg/argocdapp/reinstall.go
  internal/pkg/argocdapp/uninstall.go
Labels: refactor

#76 fix: add downloading tips and add SHA for updating github files
  internal/pkg/githubactions/githubactions.go
  internal/pkg/pluginmanager/manager.go
Labels: bug

#85 fix: #84 invalid memory address or nil pointer dereference at getFileSHA()
  internal/pkg/githubactions/githubactions.go
Labels: bug

#83 fix: #82 statemanager delete a State when uninstall failed
  internal/pkg/planmanager/result.go
  internal/pkg/statemanager/state.go
Labels: bug

#86 sha lost in Deleteworkflow
  internal/pkg/githubactions/githubactions.go
  internal/pkg/pluginmanager/downloader_test.go
Labels: bug

#92 fix: #89 #90 - logs format improved
  cmd/argocd/main.go
  cmd/argocdapp/main.go
  cmd/devstream/init.go
  cmd/githubactions/main.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/pluginmanager/manager.go
  internal/pkg/statemanager/state.go
Labels: bug
