Repository devstream-io/devstream, pull requests merged in 2022-03, with the labels that each got.

#245 Fix: Makefile e2e stage error
  Makefile
Labels: bug

#247 Feat: `dtm destroy` command
  README.md
  cmd/devstream/destroy.go
  cmd/devstream/main.go
  internal/pkg/pluginengine/cmd_destroy.go
Labels: enhancement

#260 feat: dtm verify logic and logging improvement
  cmd/devstream/verify.go
  docs/commands_in_detail/verify.md
  internal/pkg/configloader/config.go
  internal/pkg/plugin/githubactions/golang/create.go
  internal/pkg/plugin/githubactions/golang/delete.go
  internal/pkg/plugin/githubactions/golang/read.go
  internal/pkg/plugin/githubactions/golang/update.go
  internal/pkg/plugin/githubactions/nodejs/create.go
  internal/pkg/plugin/githubactions/nodejs/delete.go
  internal/pkg/plugin/githubactions/nodejs/read.go
  internal/pkg/plugin/githubactions/nodejs/update.go
  internal/pkg/plugin/githubactions/python/create.go
  internal/pkg/plugin/githubactions/python/delete.go
  internal/pkg/plugin/githubactions/python/read.go
  internal/pkg/plugin/githubactions/python/update.go
  internal/pkg/pluginengine/change.go
  internal/pkg/pluginengine/change_helper.go
  internal/pkg/pluginengine/cmd_apply.go
  internal/pkg/pluginengine/cmd_delete.go
  internal/pkg/pluginengine/cmd_verify.go
  pkg/util/github/repo.go
Labels: bug, documentation, enhancement, good first issue

#261 feat: Terraform for AWS VPC/EKS
  .gitignore
  hack/terraform/.terraform.lock.hcl
  hack/terraform/config.tf
  hack/terraform/main.tf
  hack/terraform/modules/eks/README.md
  hack/terraform/modules/eks/cluster.tf
  hack/terraform/modules/eks/cluster_roles.tf
  hack/terraform/modules/eks/control_plane_sg.tf
  hack/terraform/modules/eks/nodegroup.tf
  hack/terraform/modules/eks/output.tf
  hack/terraform/modules/eks/variables.tf
  hack/terraform/modules/eks/worker_node_roles.tf
  hack/terraform/modules/eks/worker_node_sg.tf
  hack/terraform/modules/networking/README.md
  hack/terraform/modules/networking/gateway.tf
  hack/terraform/modules/networking/output.tf
  hack/terraform/modules/networking/routing_table.tf
  hack/terraform/modules/networking/subnet.tf
  hack/terraform/modules/networking/variables.tf
  hack/terraform/modules/networking/vpc.tf
Labels: enhancement, test

#256 Feat: add jira-github-integ plugin
  Makefile
  build/package/build_linux_amd64.sh
  cmd/jiragithub/main.go
  docs/plugins/jira-github-integ_plugin.md
  examples/config.yaml
  internal/pkg/plugin/jiragithub/create.go
  internal/pkg/plugin/jiragithub/delete.go
  internal/pkg/plugin/jiragithub/helper.go
  internal/pkg/plugin/jiragithub/options.go
  internal/pkg/plugin/jiragithub/read.go
  internal/pkg/plugin/jiragithub/render.go
  internal/pkg/plugin/jiragithub/templates.go
  internal/pkg/plugin/jiragithub/update.go
  internal/pkg/plugin/jiragithub/validation.go
  internal/pkg/plugin/jiragithub/workflow.go
Labels: enhancement

#266 bug: github actions and repo scaffolding apply error after deleting repo
  go.mod
  internal/pkg/plugin/githubactions/golang/read.go
  internal/pkg/plugin/githubactions/nodejs/read.go
  internal/pkg/plugin/githubactions/python/read.go
  internal/pkg/plugin/reposcaffolding/github/golang/read.go
  pkg/util/github/repo.go
  pkg/util/github/workflow.go
Labels: bug

#269 docs: quick start
  .gitignore
  README.md
  docs/plugins/argocd_plugin.md
  docs/plugins/argocdapp_plugin.md
  docs/plugins/devlake_plugin.md
  docs/plugins/github-repo-scaffolding-golang_plugin.md
  docs/plugins/githubactions-golang_plugin.md
  docs/plugins/githubactions-nodejs_plugin.md
  docs/plugins/githubactions-python_plugin.md
  docs/plugins/gitlabci-golang_plugin.md
  docs/plugins/jenkins_plugin.md
  docs/plugins/kube-prometheus_plugin.md
  docs/plugins/trello-github-integ_plugin.md
  docs/quickstart_en.md
  docs/quickstart_zh.md
  examples/config.yaml
  examples/quickstart.yaml
Labels: documentation

#268 bug: GitHub Actions Plugin fails when Docker section doesn't exist
  internal/pkg/plugin/githubactions/golang/create.go
  internal/pkg/plugin/githubactions/golang/delete.go
  internal/pkg/plugin/githubactions/golang/options.go
  internal/pkg/plugin/githubactions/golang/render.go
  internal/pkg/plugin/githubactions/golang/update.go
Labels: bug

#270 feat: add "dependsOn" in config, add config dependency check
  README.md
  docs/plugins/argocdapp_plugin.md
  docs/plugins/githubactions-golang_plugin.md
  docs/plugins/githubactions-nodejs_plugin.md
  docs/plugins/githubactions-python_plugin.md
  docs/plugins/trello-github-integ_plugin.md
  examples/quickstart.yaml
  internal/pkg/configloader/config.go
  internal/pkg/configloader/configloader_test.go
  internal/pkg/configloader/validation.go
Labels: documentation, enhancement

#279 feat: add 'dtm delete --force' for deleting everything
  README.md
  cmd/devstream/delete.go
  cmd/devstream/main.go
  internal/pkg/pluginengine/change.go
  internal/pkg/pluginengine/change_helper.go
  internal/pkg/pluginengine/cmd_delete.go
  internal/pkg/pluginengine/pluginengine_test.go
Labels: enhancement

#280 📖 A basic Development Workflow for new contributors.
  CONTRIBUTING.md
  docs/development_workflow.md
Labels: documentation

#282 🐞 the logic with state deleting error
  internal/pkg/pluginengine/change.go
  internal/pkg/pluginengine/change_helper.go
Labels: bug

#283 feat: add log stack print for error
  pkg/util/log/logwrapper.go
Labels: enhancement

#287 fix: helm-style plugins update failed with ns error
  internal/pkg/plugin/argocd/update.go
  internal/pkg/plugin/jenkins/update.go
  internal/pkg/plugin/kubeprometheus/update.go
  pkg/util/k8s/static.go
Labels: bug

#291 fix: log stack raises errors when test cases run
  pkg/util/log/logwrapper.go
Labels: bug, enhancement

#296 fix: modify githubactions template, add blank, support push-main without PR
  internal/pkg/plugin/githubactions/golang/templates.go
Labels: bug

#301 fix: print log stack when debug
  pkg/util/log/logwrapper.go
Labels: enhancement

#308 📖: adding OWNERS & "community meeting info"
  OWNERS
  README.md
  internal/pkg/plugin/openldap/OWNERS
Labels: documentation

#312 📖: adding the description of the `tokens setting method`
  docs/plugins/github-repo-scaffolding-golang_plugin.md
  docs/plugins/githubactions-golang_plugin.md
  docs/plugins/githubactions-nodejs_plugin.md
  docs/plugins/githubactions-python_plugin.md
  docs/plugins/jira-github-integ_plugin.md
  docs/plugins/trello-github-integ_plugin.md
Labels: documentation

#309 ci: adding macos build
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-commit-message.yml
  .github/workflows/main-builder.yml
  .github/workflows/main-pushed.yml
  .github/workflows/pr-builder.yml
  .github/workflows/pr-created.yml
Labels: enhancement

#310 feat: support setting kubeconfig from env
  cmd/devstream/main.go
  pkg/util/github/github.go
  pkg/util/k8s/k8s.go
Labels: enhancement

#317 doc: fix click gitops.yaml 404
  docs/best_practices/gitops.md
Labels: documentation, good first issue

#313 feat: separate plug-in for create Trello board
  Makefile
  build/package/build_linux_amd64.sh
  cmd/trello/main.go
  docs/plugins/trello_plugin.md
  internal/pkg/plugin/trello/create.go
  internal/pkg/plugin/trello/delete.go
  internal/pkg/plugin/trello/helper.go
  internal/pkg/plugin/trello/read.go
  internal/pkg/plugin/trello/trello.go
  internal/pkg/plugin/trello/update.go
  internal/pkg/plugin/trello/validation.go
Labels: enhancement

#323 feat: add plugin outputs reference
  docs/plugins/trello-github-integ_plugin.md
  docs/plugins/trello_plugin.md
  internal/pkg/plugin/trello/helper.go
  internal/pkg/plugin/trello/trello.go
  internal/pkg/plugin/trellogithub/create.go
  internal/pkg/plugin/trellogithub/delete.go
  internal/pkg/plugin/trellogithub/helper.go
  internal/pkg/plugin/trellogithub/read.go
  internal/pkg/plugin/trellogithub/trellogithub.go
  internal/pkg/plugin/trellogithub/update.go
  internal/pkg/plugin/trellogithub/workflow.go
  internal/pkg/pluginengine/change.go
  internal/pkg/pluginengine/change_helper.go
  internal/pkg/pluginengine/cmd_apply.go
  internal/pkg/pluginengine/fillRefValueWithOutputs_test.go
  internal/pkg/pluginengine/getOutputs_test.go
  internal/pkg/statemanager/manager.go
  internal/pkg/statemanager/state.go
  pkg/util/trello/trello.go
Labels: enhancement

#328 feat: `dtm develop create-plugin` implement
  cmd/devstream/develop.go
  cmd/devstream/main.go
  internal/pkg/develop/develop.go
  internal/pkg/develop/plugin/create.go
  internal/pkg/develop/plugin/plugin.go
  internal/pkg/develop/plugin/template/NAME.go
  internal/pkg/develop/plugin/template/NAME_plugin.md.go
  internal/pkg/develop/plugin/template/README_when_create_plugin.md.go
  internal/pkg/develop/plugin/template/create.go
  internal/pkg/develop/plugin/template/delete.go
  internal/pkg/develop/plugin/template/main.go
  internal/pkg/develop/plugin/template/options.go
  internal/pkg/develop/plugin/template/read.go
  internal/pkg/develop/plugin/template/template.go
  internal/pkg/develop/plugin/template/update.go
  internal/pkg/develop/plugin/template/validate.go
Labels: enhancement

#333 fix: argocd plugin apply twice trigger update
  internal/pkg/plugin/argocd/state.go
Labels: bug

#335 docs(gitops): adding dependency logic in gitops.md
  docs/best_practices/gitops.md
  docs/plugins/argocdapp_plugin.md
  examples/gitops.yaml
Labels: documentation

#332 fix: trello card can't be created and adding delete function for trello
  internal/pkg/plugin/trello/delete.go
  internal/pkg/plugin/trello/trello.go
  internal/pkg/plugin/trello/update.go
  internal/pkg/plugin/trellogithub/create.go
  internal/pkg/plugin/trellogithub/update.go
  internal/pkg/plugin/trellogithub/workflow.go
  internal/pkg/pluginengine/change.go
  pkg/util/trello/trello.go
Labels: bug, enhancement

#341 docs: add output documentation
  docs/index.md
  docs/output.md
Labels: documentation

#346 refactor(trello): consistent entry logic with other plugins
  internal/pkg/plugin/trello/create.go
  internal/pkg/plugin/trello/delete.go
  internal/pkg/plugin/trello/helper.go
  internal/pkg/plugin/trello/read.go
  internal/pkg/plugin/trello/update.go
  internal/pkg/plugin/trello/validate.go
Labels: refactor

#337 Feat: version improvement
  Makefile
  cmd/devstream/init.go
  docs/best_practices/gitops.md
  docs/quickstart_en.md
  docs/quickstart_zh.md
  internal/pkg/configloader/config.go
  internal/pkg/pluginmanager/manager.go
  internal/pkg/pluginmanager/pbdownloader.go
  internal/pkg/pluginmanager/pluginmd5_suit_test.go
  internal/pkg/pluginmanager/pluginmd5_test.go
  pkg/util/md5/helper.go
  pkg/util/md5/md5.go
  pkg/util/md5/md5_test.go
Labels: enhancement

#349 fix: main-builder.yaml -> main-pushed.yml at README.md
  README.md
Labels: bug

#322 ci: e2e-test from `actions` to `eks`
  .github/workflows/e2e-test.yml
  .github/workflows/main-pushed.yml
  .github/workflows/pr-created.yml
  Makefile
  README.md
  test/e2e/yaml/e2e-config.yaml
Labels: ci

#352 refactor(cmd): keep all plugins dirname-in-cmd == plugin-name
  Makefile
  build/package/build_linux_amd64.sh
  cmd/plugin/argocd/main.go
  cmd/plugin/argocdapp/main.go
  cmd/plugin/devlake/main.go
  cmd/plugin/github-repo-scaffolding-golang/main.go
  cmd/plugin/githubactions-golang/main.go
  cmd/plugin/githubactions-nodejs/main.go
  cmd/plugin/githubactions-python/main.go
  cmd/plugin/gitlabci-golang/main.go
  cmd/plugin/jenkins/main.go
  cmd/plugin/jiragithub/main.go
  cmd/plugin/kubeprometheus/main.go
  cmd/plugin/openldap/main.go
  cmd/plugin/trello/main.go
  cmd/plugin/trellogithub/main.go
  docs/creating_a_plugin.md
Labels: refactor

#354 fix: change main_go_dir to `cmd/plugin/`
  internal/pkg/develop/plugin/template/main.go
Labels: bug

#362 feat: trigger GitHub actions after some specific comments
  .github/workflows/pr-created.yml
  .github/workflows/ut-linux.yml
  .github/workflows/ut-mac.yml
  .gitignore
Labels: ci

#360 Automated Release script and workflow
  .github/workflows/automated-release.yml
  build/package/auto-release-darwin-arm64.sh
  build/package/upload_assets.sh
Labels: enhancement

#368 fix: GitHub actions error - API rate limit exceeded
  .github/workflows/ut-linux.yml
  .github/workflows/ut-mac.yml
  Makefile
  pkg/util/github/github_test.go
Labels: bug

#370 fix: install goimports at `main builder` & `automated-release` workflow
  .github/workflows/automated-release.yml
  .github/workflows/main-builder.yml
Labels: bug
