Repository devstream-io/devstream, pull requests merged in 2022-08, with the labels that each got.

#937 fix: issue template error with documentation type
  .github/ISSUE_TEMPLATE/documentation.yaml
Labels: bug

#992 refactor: unify templates delim
  internal/pkg/develop/plugin/plugin.go
  internal/pkg/develop/plugin/template/NAME.go
  internal/pkg/develop/plugin/template/NAME_plugin.md.go
  internal/pkg/develop/plugin/template/NAME_plugin.md.tpl
  internal/pkg/develop/plugin/template/NAME_plugin.zh.md.go
  internal/pkg/develop/plugin/template/NAME_plugin.zh.md.tpl
  internal/pkg/develop/plugin/template/README_when_create_plugin.md.go
  internal/pkg/develop/plugin/template/config.go
  internal/pkg/develop/plugin/template/create.go
  internal/pkg/develop/plugin/template/delete.go
  internal/pkg/develop/plugin/template/main.go
  internal/pkg/develop/plugin/template/options.go
  internal/pkg/develop/plugin/template/read.go
  internal/pkg/develop/plugin/template/template.go
  internal/pkg/develop/plugin/template/update.go
  internal/pkg/develop/plugin/template/validate.go
  internal/pkg/show/config/gen_embed.tpl
  internal/pkg/show/config/gen_embed_var.go
  staging/dtm-repo-scaffolding-golang/helm/_app_name_/templates/deployment.yaml.tpl
Labels: refactor

#990 chore: remove magic value and useless code
  internal/pkg/plugin/argocdapp/create.go
  internal/pkg/plugin/argocdapp/delete.go
  internal/pkg/plugin/common/helm/helm.go
  internal/pkg/plugin/devlake/create.go
  internal/pkg/plugin/devlake/delete.go
  internal/pkg/plugin/githubactions/golang/create.go
  internal/pkg/plugin/githubactions/golang/delete.go
  internal/pkg/plugin/githubactions/golang/update.go
  internal/pkg/plugin/githubactions/nodejs/create.go
  internal/pkg/plugin/githubactions/nodejs/delete.go
  internal/pkg/plugin/githubactions/nodejs/update.go
  internal/pkg/plugin/githubactions/python/create.go
  internal/pkg/plugin/githubactions/python/delete.go
  internal/pkg/plugin/githubactions/python/update.go
  internal/pkg/plugininstaller/github/installer.go
  internal/pkg/plugininstaller/kubectl/installer.go
  internal/pkg/plugininstaller/kubectl/installer_test.go
  pkg/util/kubectl/cmd.go
  pkg/util/kubectl/cmd_test.go
Labels: refactor

#980 Feat: Adding New Plugin `harbor-docker`
  cmd/plugin/harbor-docker/main.go
  docs/plugins/harbor-docker.md
  docs/plugins/harbor-docker.zh.md
  internal/pkg/develop/plugin/template/read.go
  internal/pkg/develop/plugin/template/update.go
  internal/pkg/plugin/harbordocker/create.go
  internal/pkg/plugin/harbordocker/delete.go
  internal/pkg/plugin/harbordocker/harbordocker.go
  internal/pkg/plugin/harbordocker/options.go
  internal/pkg/plugin/harbordocker/read.go
  internal/pkg/plugin/harbordocker/sh/LICENSE
  internal/pkg/plugin/harbordocker/sh/common.sh
  internal/pkg/plugin/harbordocker/sh/harbor.tmpl.yml
  internal/pkg/plugin/harbordocker/sh/install.sh
  internal/pkg/plugin/harbordocker/sh/prepare
  internal/pkg/plugin/harbordocker/update.go
  internal/pkg/plugin/harbordocker/validate.go
  internal/pkg/plugininstaller/common/repo.go
  internal/pkg/plugininstaller/docker/compose.go
  internal/pkg/plugininstaller/docker/installer.go
  internal/pkg/show/config/embed_gen.go
  internal/pkg/show/config/plugins/harbor-docker.yaml
  pkg/util/docker/docker.go
  pkg/util/docker/dockersh/compose.go
  pkg/util/docker/dockersh/exec.go
  pkg/util/docker/dockersh/operator.go
  pkg/util/file/file.go
  pkg/util/k8s/static.go
Labels: enhancement
