Repository devstream-io/devstream, pull requests merged in 2022-11, with the labels that each got.

#1247 Refactor: Remove `types` Package(vars.go and error.go) in `backend` Package
  internal/pkg/backend/backend.go
  internal/pkg/backend/backend_test.go
  internal/pkg/backend/s3/validate.go
  internal/pkg/backend/s3/validate_test.go
  internal/pkg/backend/types/error.go
  internal/pkg/backend/types/vars.go
  internal/pkg/configmanager/configmanager_test.go
Labels: refactor

#1248 Refactor: `configmanager` Package Enhancement
  internal/pkg/configmanager/config.go
  internal/pkg/configmanager/config_test.go
  internal/pkg/configmanager/configmanager.go
  internal/pkg/configmanager/configmanager_test.go
  internal/pkg/configmanager/rawconfig.go
  internal/pkg/configmanager/tool.go
Labels: refactor

#1252 Feat: Remove pluginDir Item in Config File
  cmd/devstream/apply.go
  cmd/devstream/common.go
  cmd/devstream/delete.go
  cmd/devstream/destroy.go
  cmd/devstream/init.go
  cmd/devstream/show.go
  cmd/devstream/verify.go
  docs/best-practices/air-gapped-deployment.zh.md
  docs/core-concepts/config.md
  docs/core-concepts/config.zh.md
  docs/core-concepts/stateconfig.md
  docs/plugins/ci-generic.md
  docs/plugins/ci-generic.zh.md
  docs/plugins/helm-installer/helm-installer.zh.md
  docs/plugins/repo-scaffolding.md
  docs/plugins/zentao.md
  docs/plugins/zentao.zh.md
  examples/gitops.yaml
  examples/quickstart.yaml
  go.mod
  internal/pkg/configmanager/config.go
  internal/pkg/configmanager/config_test.go
  internal/pkg/configmanager/configmanager.go
  internal/pkg/configmanager/configmanager_test.go
  internal/pkg/configmanager/rawconfig.go
  internal/pkg/configmanager/tool.go
  internal/pkg/pluginengine/cmd_apply.go
  internal/pkg/pluginengine/cmd_delete.go
  internal/pkg/pluginengine/cmd_destroy.go
  internal/pkg/pluginengine/cmd_verify.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/pluginmanager/manager.go
  internal/pkg/show/config/default.yaml
  internal/pkg/show/config/templates/gitops.yaml
  internal/pkg/show/config/templates/quickstart.yaml
  internal/pkg/show/status/status.go
  mkdocs.yml
  test/e2e/yaml/e2e-config.yaml
  test/e2e/yaml/e2e-trello-github-tools.yaml
Labels: enhancement

#1261 Feat: Add More Logs in The Top Level of Plugins
  internal/pkg/plugin/argocdapp/create.go
  internal/pkg/pluginengine/change.go
Labels: bug, enhancement

#1277 fix: output not render error
  internal/pkg/pluginengine/outputs.go
  internal/pkg/pluginengine/pluginengine_test.go
  internal/pkg/statemanager/state.go
Labels: bug
