Repository devstream-io/devstream, pull requests merged in 2022-04, with the labels that each got.

#382 docs: update stream to devstream
  docs/development_workflow.md
Labels: documentation

#390 docs: change `demo` to `repo`
  docs/output.md
Labels: bug, documentation

#398 ci: optimize ci pipeline
  .github/workflows/e2e-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-commit-message.yml
  .github/workflows/main-builder.yml
  .github/workflows/main.yml
  .github/workflows/pr-builder.yml
  .github/workflows/pr.yml
  README.md
  docs/README_zh.md
Labels: ci

#408 docs(README): replace discord badge with slack
  README.md
Labels: documentation

#413 docs: add `fig` doc
  docs/autocomplete.md
  docs/images/cmd-help.gif
  docs/images/cmd-make.gif
  docs/images/cmd-show-plugins.gif
  docs/images/fig-intro.gif
  docs/images/fig-terminal.png
  docs/index.md
Labels: documentation
