Repository devstream-io/devstream, pull requests merged in 2022-05, with the labels that each got.

#498 📖 `Docs`: update README_zh.md
  docs/README_zh.md
Labels: documentation

#499 📖 `Docs`: fix some links error
  CONTRIBUTING.md
  README.md
Labels: documentation

#545 fmt: remove unused dependencies
  cmd/devstream/develop.go
Labels: bug

#548 docs: add s3 remote state doc
  docs/core-concepts/config.md
  docs/core-concepts/state.md
  docs/core-concepts/stateconfig.md
  mkdocs.yml
Labels: documentation

#591 fix:gopath is no longer set
  Makefile
Labels: enhancement, ci

#626 feat: add editorconfig
  .editorconfig
Labels: enhancement
