Repository devstream-io/devstream, pull requests merged in 2022-06, with the labels that each got.

#655 Feat: Config Logic Enhancement
  cmd/devstream/init.go
  docs/best-practices/gitops.md
  docs/quickstart_en.md
  docs/quickstart_zh.md
  examples/gitops.yaml
  examples/quickstart.yaml
  examples/tools-gitops.yaml
  examples/tools-quickstart.yaml
  examples/variables-gitops.yaml
  internal/pkg/configloader/config.go
  internal/pkg/configloader/configloader_suite_test.go
  internal/pkg/configloader/configloader_test.go
  internal/pkg/configloader/coreconfig.go
  internal/pkg/configloader/generalconfig_test.go
  internal/pkg/configloader/toolconfig.go
  internal/pkg/configloader/validation.go
  internal/pkg/configloader/variables.go
  internal/pkg/pluginengine/cmd_apply.go
  internal/pkg/pluginengine/cmd_delete.go
  internal/pkg/pluginengine/cmd_destroy.go
  internal/pkg/pluginengine/cmd_verify.go
  internal/pkg/show/status/status.go
Labels: enhancement, refactor

#668 fix: duplicate error output
  cmd/devstream/apply.go
  cmd/devstream/main.go
Labels: bug

#640 feat: new plugin - tekton
  cmd/plugin/tekton/main.go
  docs/plugins/tekton.md
  internal/pkg/plugin/common/helm/helm.go
  internal/pkg/plugin/tekton/create.go
  internal/pkg/plugin/tekton/delete.go
  internal/pkg/plugin/tekton/read.go
  internal/pkg/plugin/tekton/state.go
  internal/pkg/plugin/tekton/tekton.go
  internal/pkg/plugin/tekton/update.go
  internal/pkg/plugin/tekton/validate.go
  internal/pkg/show/config/plugins/tekton.yaml
  internal/pkg/show/status/status.go
Labels: duplicate

#691 update go version to 1.18
  .github/workflows/automated-release.yml
  .github/workflows/e2e-test.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  README.md
  docs/README_zh.md
  docs/core-concepts/dependencies.md
  docs/plugins/github-repo-scaffolding-golang.md
  docs/plugins/githubactions-golang.md
  docs/quickstart.md
  docs/quickstart.zh.md
  examples/gitops.yaml
  examples/quickstart.yaml
  go.mod
  go.sum
  internal/pkg/plugin/githubactions/golang/templates.go
  internal/pkg/show/config/plugins/githubactions-golang.yaml
  staging/dtm-repo-scaffolding-golang/go.mod.tpl
  test/e2e/yaml/e2e-tools.yaml
Labels: enhancement, ci
