Repository devstream-io/devstream, pull requests merged in 2022-01, with the labels that each got.

#101 Fix: fix some grammatical errors in logs
  cmd/devstream/install.go
  internal/pkg/pluginmanager/manager.go
Labels: bug

#70 feat: adding ConcurrentMap
  internal/pkg/container/concurrentmap/concurrentmap.go
  internal/pkg/planmanager/plan.go
  internal/pkg/planmanager/result.go
  internal/pkg/statemanager/manager.go
  internal/pkg/statemanager/manager_test.go
  internal/pkg/statemanager/state.go
  internal/pkg/statemanager/states.go
Labels: enhancement, refactor

#60 test: adding ginkgo BDD framework for e2e testing & UT
  go.mod
  go.sum
  internal/pkg/planmanager/plan_test.go
  internal/pkg/planmanager/planmanager_suite_test.go
  internal/pkg/planmanager/planmanager_test.go
Labels: test

#106 Reflactor: Create a New plugin Package to Store the Code with All the Build-in Plugins
  cmd/argocd/main.go
  cmd/argocdapp/main.go
  cmd/githubactions/main.go
  go.sum
  internal/pkg/plugin/argocd/argocd.go
  internal/pkg/plugin/argocd/install.go
  internal/pkg/plugin/argocd/params.go
  internal/pkg/plugin/argocd/reinstall.go
  internal/pkg/plugin/argocd/uninstall.go
  internal/pkg/plugin/argocdapp/argocdapp.go
  internal/pkg/plugin/argocdapp/install.go
  internal/pkg/plugin/argocdapp/params.go
  internal/pkg/plugin/argocdapp/reinstall.go
  internal/pkg/plugin/argocdapp/template.go
  internal/pkg/plugin/argocdapp/uninstall.go
  internal/pkg/plugin/githubactions/githubactions.go
  internal/pkg/plugin/githubactions/golang/templates.go
  internal/pkg/plugin/githubactions/install.go
  internal/pkg/plugin/githubactions/nodejs/templates.go
  internal/pkg/plugin/githubactions/python/templates.go
  internal/pkg/plugin/githubactions/reinstall.go
  internal/pkg/plugin/githubactions/uninstall.go
  internal/pkg/plugin/githubactions/workflow.go
Labels: refactor

#107 doc: code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#97 progress bar for download
  go.mod
  go.sum
  internal/pkg/pluginmanager/manager.go
  internal/pkg/pluginmanager/pbdownloader.go
Labels: enhancement

#108 Feat: Add a Parameter -p (--plugins-dir)
  .gitignore
  cmd/devstream/main.go
  internal/pkg/backend/local/local.go
  internal/pkg/plugin/githubactions/githubactions.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/pluginmanager/downloader.go
  internal/pkg/pluginmanager/manager.go
Labels: enhancement

#109 change command 'install' to 'apply'
  cmd/devstream/apply.go
  cmd/devstream/main.go
  go.mod
  go.sum
Labels: enhancement

#110 Feat: Use viper to read in the config.yaml
  cmd/devstream/apply.go
  cmd/devstream/init.go
  cmd/devstream/main.go
  internal/pkg/configloader/config.go
  internal/pkg/pluginmanager/pbdownloader.go
Labels: enhancement

#117 check file content md5
  internal/pkg/pluginmanager/manager.go
  internal/pkg/pluginmanager/md5.go
  internal/pkg/pluginmanager/pbdownloader.go
Labels: enhancement

#116 feat: setup e2e env
  .gitignore
  docs/project_layout.md
  hack/README.md
  hack/e2e/e2e-down.sh
  hack/e2e/e2e-up.sh
  hack/e2e/kind.yaml
  test/e2e/suites.go
  test/smoke/smoke.py
Labels: test

#124 Feat: Automated Local E2E Testing - Test 0 to 1
  .gitignore
  Makefile
  cmd/argocd/main.go
  cmd/argocdapp/main.go
  cmd/githubactions/main.go
  internal/pkg/plugin/argocd/ishealthy.go
  internal/pkg/plugin/argocdapp/ishealthy.go
  internal/pkg/plugin/githubactions/ishealthy.go
  internal/pkg/pluginengine/check.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/util/os/exec.go
  test/smoke/smoke.go
  test/smoke/smoke.py
Labels: test

#126 Feat: ArgoCD health check implement
  cmd/devstream/main.go
  go.mod
  go.sum
  internal/pkg/plugin/argocd/ishealthy.go
  internal/pkg/pluginengine/check.go
  internal/pkg/pluginengine/helper.go
  internal/pkg/pluginengine/plugin.go
  internal/pkg/util/k8s/k8s.go
  test/smoke/smoke.go
Labels: enhancement

#125 add github actions for code coverage, switch var
  examples/config.yaml
  internal/pkg/plugin/githubactions/githubactions.go
  internal/pkg/plugin/githubactions/githubactions_test.go
  internal/pkg/plugin/githubactions/golang/templates.go
  internal/pkg/plugin/githubactions/install.go
  internal/pkg/plugin/githubactions/jobs.go
  internal/pkg/plugin/githubactions/workflow.go
Labels: enhancement

#127 Feat: IsHealthy() for Argocdapp implement
  go.mod
  go.sum
  hack/README.md
  hack/switch_k8s_dep_version.sh
  internal/pkg/plugin/argocdapp/ishealthy.go
  internal/pkg/util/k8s/argocd.go
  internal/pkg/util/k8s/k8s.go
Labels: enhancement

#132 auto comment by githubacions
  examples/config.yaml
  internal/pkg/plugin/githubactions/golang/templates.go
  internal/pkg/plugin/githubactions/jobs.go
Labels: enhancement

#135 feat: plugin supports multiple instances
  examples/config.yaml
  go.mod
  internal/pkg/configloader/config.go
  internal/pkg/planmanager/plan_apply.go
  internal/pkg/planmanager/plan_helper.go
  internal/pkg/plugin/argocd/argocd.go
  internal/pkg/plugin/argocdapp/install.go
  internal/pkg/plugin/argocdapp/uninstall.go
Labels: enhancement, BREAKING CHANGE

#134 Feat: Adding kube-prometheus plugin
  Makefile
  cmd/kubeprometheus/main.go
  docs/kube-prometheus_plugin.md
  examples/config.yaml
  internal/pkg/plugin/kubeprometheus/install.go
  internal/pkg/plugin/kubeprometheus/ishealthy.go
  internal/pkg/plugin/kubeprometheus/reinstall.go
  internal/pkg/plugin/kubeprometheus/uninstall.go
  internal/pkg/util/helm/helm.go
  internal/pkg/util/helm/param.go
Labels: enhancement

#139 Refactor: update argocd to use util/helm
  internal/pkg/plugin/argocd/argocd.go
  internal/pkg/plugin/argocd/install.go
  internal/pkg/plugin/argocd/params.go
  internal/pkg/plugin/argocd/reinstall.go
  internal/pkg/plugin/argocd/uninstall.go
Labels: refactor

#140 Feat: exposed more params with the plugins used helm
  docs/argocd_plugin.md
  docs/kube-prometheus_plugin.md
  examples/config.yaml
  internal/pkg/util/helm/helm.go
  internal/pkg/util/helm/param.go
Labels: enhancement

#141 Feat: health-check for kube-prometheus
  internal/pkg/plugin/argocd/ishealthy.go
  internal/pkg/plugin/kubeprometheus/ishealthy.go
  internal/pkg/util/k8s/k8s.go
Labels: enhancement

#142 Feat: Adding config validation for dtm
  cmd/devstream/init.go
  cmd/devstream/verify.go
  internal/pkg/configloader/config.go
  internal/pkg/configloader/validation.go
  internal/pkg/pluginengine/apply.go
  internal/pkg/pluginengine/check.go
  internal/pkg/pluginengine/delete.go
Labels: enhancement

#145 Feat: Adding config validation for all plugins
  internal/pkg/configloader/validation.go
  internal/pkg/plugin/argocd/install.go
  internal/pkg/plugin/argocd/ishealthy.go
  internal/pkg/plugin/argocd/reinstall.go
  internal/pkg/plugin/argocd/uninstall.go
  internal/pkg/plugin/argocd/validation.go
  internal/pkg/plugin/argocdapp/install.go
  internal/pkg/plugin/argocdapp/ishealthy.go
  internal/pkg/plugin/argocdapp/reinstall.go
  internal/pkg/plugin/argocdapp/uninstall.go
  internal/pkg/plugin/argocdapp/validation.go
  internal/pkg/plugin/githubactions/githubactions.go
  internal/pkg/plugin/githubactions/jobs.go
  internal/pkg/plugin/githubactions/validation.go
  internal/pkg/plugin/githubactions/workflow.go
  internal/pkg/plugin/kubeprometheus/install.go
  internal/pkg/plugin/kubeprometheus/ishealthy.go
  internal/pkg/plugin/kubeprometheus/reinstall.go
  internal/pkg/plugin/kubeprometheus/uninstall.go
  internal/pkg/plugin/kubeprometheus/validation.go
  internal/pkg/plugin/trellogithub/trellogithub.go
  internal/pkg/plugin/trellogithub/validation.go
  internal/pkg/plugin/trellogithub/workflowhelper.go
  internal/pkg/util/helm/validation.go
Labels: enhancement

#151 Logging improvement
  cmd/argocd/main.go
  cmd/argocdapp/main.go
  cmd/devstream/apply.go
  cmd/devstream/delete.go
  cmd/devstream/init.go
  cmd/devstream/main.go
  cmd/devstream/verify.go
  cmd/githubactions/main.go
  cmd/kubeprometheus/main.go
  cmd/trellogithub/main.go
  go.mod
  go.sum
  internal/pkg/backend/local/local.go
  internal/pkg/configloader/config.go
  internal/pkg/log/log.go
  internal/pkg/log/log_test.go
  internal/pkg/log/logwrapper.go
  internal/pkg/log/symbol.go
  internal/pkg/planmanager/plan_apply.go
  internal/pkg/planmanager/plan_delete.go
  internal/pkg/planmanager/plan_helper.go
  internal/pkg/planmanager/result.go
  internal/pkg/plugin/argocd/install.go
  internal/pkg/plugin/argocd/ishealthy.go
  internal/pkg/plugin/argocd/reinstall.go
  internal/pkg/plugin/argocd/uninstall.go
  internal/pkg/plugin/argocdapp/argocdapp.go
  internal/pkg/plugin/argocdapp/install.go
  internal/pkg/plugin/argocdapp/ishealthy.go
  internal/pkg/plugin/argocdapp/reinstall.go
  internal/pkg/plugin/argocdapp/uninstall.go
  internal/pkg/plugin/githubactions/githubactions.go
  internal/pkg/plugin/githubactions/install.go
  internal/pkg/plugin/githubactions/ishealthy.go
  internal/pkg/plugin/githubactions/reinstall.go
  internal/pkg/plugin/githubactions/uninstall.go
  internal/pkg/plugin/kubeprometheus/install.go
  internal/pkg/plugin/kubeprometheus/ishealthy.go
  internal/pkg/plugin/kubeprometheus/reinstall.go
  internal/pkg/plugin/kubeprometheus/uninstall.go
  internal/pkg/plugin/trellogithub/install.go
  internal/pkg/plugin/trellogithub/ishealthy.go
  internal/pkg/plugin/trellogithub/reinstall.go
  internal/pkg/plugin/trellogithub/trellogithub.go
  internal/pkg/plugin/trellogithub/uninstall.go
  internal/pkg/pluginengine/apply.go
  internal/pkg/pluginengine/check.go
  internal/pkg/pluginengine/delete.go
  internal/pkg/pluginengine/helper.go
  internal/pkg/pluginmanager/downloader.go
  internal/pkg/pluginmanager/manager.go
  internal/pkg/pluginmanager/pbdownloader.go
  internal/pkg/statemanager/states_map.go
  internal/pkg/util/helm/helm.go
Labels: enhancement

#154 Feat: Implementing Install() for github-reposcaffolding-golang plugin
  .gitignore
  docs/github-repo-scaffolding-golang_plugin.md
  examples/config.yaml
  internal/pkg/plugin/reposcaffolding/github/golang/golang.go
  internal/pkg/plugin/reposcaffolding/github/golang/install.go
  internal/pkg/plugin/reposcaffolding/github/golang/param.go
  internal/pkg/plugin/reposcaffolding/github/golang/validation.go
  internal/pkg/util/downloader/downloader.go
  internal/pkg/util/github/github.go
  internal/pkg/util/github/github_test.go
  internal/pkg/util/zip/zip.go
  internal/pkg/util/zip/zip_suit_test.go
  internal/pkg/util/zip/zip_test.go
Labels: enhancement

#155 Makefile version improve
  Makefile
  build/package/Dockerfile
  build/package/build_linux_amd64.sh
  internal/pkg/version/version.go
Labels: enhancement

#157 Feat: Let github-repo-scaffolding-golang the the main branch code of the template repo
  internal/pkg/plugin/reposcaffolding/github/golang/golang.go
  internal/pkg/plugin/reposcaffolding/github/golang/install.go
  internal/pkg/util/downloader/downloader.go
  internal/pkg/util/downloader/downloader_test.go
  internal/pkg/util/github/github.go
  internal/pkg/util/zip/zip.go
Labels: enhancement

#158 Chore: Quality-of-Life Improvements
  Makefile
  cmd/devstream/main.go
  examples/config.yaml
  internal/pkg/log/log.go
  internal/pkg/log/logwrapper.go
  internal/pkg/pluginengine/apply.go
  internal/pkg/pluginengine/helper.go
  internal/pkg/util/zip/zip.go
Labels: enhancement

#159 Feat: Adding trello util
  cmd/devstream/main.go
  go.mod
  go.sum
  internal/pkg/util/trello/trello.go
  internal/pkg/util/trello/trello_suit_test.go
  internal/pkg/util/trello/trello_test.go
Labels: enhancement

#161 update log statements
  internal/pkg/plugin/trellogithub/install.go
  internal/pkg/plugin/trellogithub/reinstall.go
Labels: bug

#173 Feat: delete namespace when uninstall argocd & kube-prometheus
  examples/config.yaml
  internal/pkg/plugin/argocd/reinstall.go
  internal/pkg/plugin/argocd/uninstall.go
  internal/pkg/plugin/kubeprometheus/reinstall.go
  internal/pkg/plugin/kubeprometheus/uninstall.go
  pkg/util/helm/helm.go
  pkg/util/k8s/github_test.go
  pkg/util/k8s/k8s.go
  pkg/util/k8s/k8s_suite_test.go
  pkg/util/k8s/static.go
  pkg/util/k8s/workload.go
Labels: enhancement
