Repository devstream-io/devstream, pull requests merged in 2022-07, with the labels that each got.

#837 feat: new plugin jenkins-pipeline-kubernetes && jenkins plugin enhancement
  cmd/plugin/jenkins-pipeline-kubernetes/main.go
  docs/plugins/jenkins-pipeline-kubernetes.md
  docs/plugins/jenkins-pipeline-kubernetes.zh.md
  docs/plugins/jenkins.md
  docs/plugins/jenkins.zh.md
  go.mod
  go.sum
  internal/pkg/plugin/jenkinspipelinekubernetes/client.go
  internal/pkg/plugin/jenkinspipelinekubernetes/create.go
  internal/pkg/plugin/jenkinspipelinekubernetes/delete.go
  internal/pkg/plugin/jenkinspipelinekubernetes/jenkinspipelinekubernetes.go
  internal/pkg/plugin/jenkinspipelinekubernetes/jenkinspipelinekubernetes_suite_test.go
  internal/pkg/plugin/jenkinspipelinekubernetes/job-template.xml
  internal/pkg/plugin/jenkinspipelinekubernetes/options.go
  internal/pkg/plugin/jenkinspipelinekubernetes/read.go
  internal/pkg/plugin/jenkinspipelinekubernetes/update.go
  internal/pkg/plugin/jenkinspipelinekubernetes/validate.go
  internal/pkg/show/config/embed_gen.go
  internal/pkg/show/config/plugins/jenkins-pipeline-kubernetes.yaml
  internal/pkg/show/config/plugins/jenkins.yaml
Labels: enhancement

#867 refactor: kubectl plugin installer
  go.mod
  go.sum
  internal/pkg/plugin/argocd/read.go
  internal/pkg/plugin/argocdapp/argocdapp.go
  internal/pkg/plugin/argocdapp/create.go
  internal/pkg/plugin/argocdapp/delete.go
  internal/pkg/plugin/argocdapp/options.go
  internal/pkg/plugin/argocdapp/read.go
  internal/pkg/plugin/argocdapp/state.go
  internal/pkg/plugin/argocdapp/template.go
  internal/pkg/plugin/argocdapp/validate.go
  internal/pkg/plugin/devlake/create.go
  internal/pkg/plugin/devlake/delete.go
  internal/pkg/plugin/devlake/devlake.go
  internal/pkg/plugin/devlake/options.go
  internal/pkg/plugin/devlake/read.go
  internal/pkg/plugin/devlake/state.go
  internal/pkg/plugininstaller/helm/installer.go
  internal/pkg/plugininstaller/helm/state.go
  internal/pkg/plugininstaller/kubectl/installer.go
  internal/pkg/plugininstaller/kubectl/utils.go
  internal/pkg/plugininstaller/plugininstaller.go
  internal/pkg/plugininstaller/util/file.go
  internal/pkg/plugininstaller/util/k8s.go
  pkg/util/downloader/downloader.go
Labels: refactor

#888 docs: document translation rules
  docs/development/translation.md
  docs/development/translation.zh.md
  mkdocs.yml
Labels: documentation
